config/routes.rb
Rails.application.routes.draw do
  get 'technology/index'
  get 'economy/index'
  get 'game/index'
  get 'anime/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/index'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  get 'toppages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveModel::Serializers::JSON
  def self.thumbnails_in(url)
      require 'rss'
      rss = RSS::Parser.parse(url)
      
      return rss.items
  end
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
end

app/controllers/anime_controller.rb
class AnimeController < ApplicationController
  def index
     @items = Article.thumbnails_in("http://anicobin.ldblog.jp/index.rdf")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/economy_controller.rb
class EconomyController < ApplicationController
  def index
     @items = Article.thumbnails_in("https://news.nifty.com/rss/topics_economy.xml")
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
     @items = Article.thumbnails_in("https://rss.allabout.co.jp/aa/latest/ch/ch_game/")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/technology_controller.rb
class TechnologyController < ApplicationController
  def index
     @items = Article.thumbnails_in("https://jp.techcrunch.com/feed/")
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @items = Article.thumbnails_in("https://news.yahoo.co.jp/pickup/rss.xml")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/anime_helper.rb
module AnimeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/economy_helper.rb
module EconomyHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/technology_helper.rb
module TechnologyHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/anime/index.html.erb
<ul class="nav nav-tabs nav-justified anime-tag" role="tablist">
    <li class="nav-item ">
      <a class="nav-link bg-secondary text-white" href="/">トップ</a>
    </li>
    <li class="nav-item anime-tag">
      <a class="nav-link bg-danger text-white activate" href="/anime/index">アニメ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-warning text-white" href="/game/index">ゲーム</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-success text-white" href="/economy/index">経済</a>
    </li>

    <li class="nav-item">
      <a class="nav-link bg-primary text-white "href="/technology/index">テクノロジー</a>
    </li>
  </ul>




<!-- サムネイル表示場所-->

  <div class="row justify-content-around">
  

  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[1].link %> target="_blank" title=<%= @items[1].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[1].link%>>
    </a>
    <p><%= @items[1].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[2].link %> target="_blank" title=<%= @items[2].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[2].link%>>
    </a>
    <p><%= @items[2].title %></p>
  </div>
  
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[3].link %> target="_blank" title=<%= @items[3].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[3].link%>>
    </a>
    <p><%= @items[3].title %></p>
  </div>
  
  </div>
  
  
  <div class="row justify-content-around">
    
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[4].link %> target="_blank" title=<%= @items[4].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[4].link%>>
    </a>
    <p><%= @items[4].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[5].link %> target="_blank" title=<%= @items[5].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[5].link%>>
    </a>
    <p><%= @items[5].title %></p>
  </div>
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[6].link %> target="_blank" title=<%= @items[6].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[6].link%>>
    </a>
    <p><%= @items[6].title %></p>
  </div>
  
  
  
  
  <!--
  <% @items.each do |item| %>
  <div class="nav-item mt-3 col-md-3  thum">
    <%= link_to item.link do %>
      <%= image_tag "http://capture.heartrails.com/?" + item.link %>
    <% end %>
    <p><%= item.title %></p>
  </div>
  </div>
<% end %>
  -->
  
  </div>

app/views/economy/index.html.erb
<ul class="nav nav-tabs nav-justified economy-tag" role="tablist">
    <li class="nav-item">
      <a class="nav-link bg-secondary text-white" href="/">トップ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-danger text-white" href="/anime/index">アニメ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-warning text-white" href="/game/index">ゲーム</a>
    </li>
    <li class="nav-item economy-tag">
      <a class="nav-link bg-success text-white activate" href="/economy/index">経済</a>
    </li>

    <li class="nav-item">
      <a class="nav-link bg-primary text-white "href="/technology/index">テクノロジー</a>
    </li>
  </ul>




<!-- サムネイル表示場所-->

  <div class="row justify-content-around">
  

  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[1].link %> target="_blank" title=<%= @items[1].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[1].link%>>
    </a>
    <p><%= @items[1].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[2].link %> target="_blank" title=<%= @items[2].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[2].link%>>
    </a>
    <p><%= @items[2].title %></p>
  </div>
  
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[3].link %> target="_blank" title=<%= @items[3].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[3].link%>>
    </a>
    <p><%= @items[3].title %></p>
  </div>
  
  </div>
  
  
  <div class="row justify-content-around">
    
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[4].link %> target="_blank" title=<%= @items[4].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[4].link%>>
    </a>
    <p><%= @items[4].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[5].link %> target="_blank" title=<%= @items[5].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[5].link%>>
    </a>
    <p><%= @items[5].title %></p>
  </div>
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[6].link %> target="_blank" title=<%= @items[6].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[6].link%>>
    </a>
    <p><%= @items[6].title %></p>
  </div>
  
  
  
  
  <!--
  <% @items.each do |item| %>
  <div class="item mt-3 col-md-3 thum">
    <%= link_to item.link do %>
      <%= image_tag "http://capture.heartrails.com/?" + item.link %>
    <% end %>
    <p><%= item.title %></p>
  </div>
<% end %>
  -->
  
  </div>

app/views/game/index.html.erb
<ul class="nav nav-tabs nav-justified game-tag" role="tablist">
    <li class="nav-item">
      <a class="nav-link bg-secondary text-white" href="/">トップ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-danger text-white" href="/anime/index">アニメ</a>
    </li>
    <li class="nav-item game-tag">
      <a class="nav-link bg-warning text-white activate" href="/game/index">ゲーム</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-success text-white" href="/economy/index">経済</a>
    </li>

    <li class="nav-item">
      <a class="nav-link bg-primary text-white "href="/technology/index">テクノロジー</a>
    </li>
  </ul>




<!-- サムネイル表示場所-->

  <div class="row justify-content-around">
  

  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[1].link %> target="_blank" title=<%= @items[1].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[1].link%>>
    </a>
    <p><%= @items[1].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[2].link %> target="_blank" title=<%= @items[2].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[2].link%>>
    </a>
    <p><%= @items[2].title %></p>
  </div>
  
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[3].link %> target="_blank" title=<%= @items[3].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[3].link%>>
    </a>
    <p><%= @items[3].title %></p>
  </div>
  
  </div>
  
  
  <div class="row justify-content-around">
    
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[4].link %> target="_blank" title=<%= @items[4].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[4].link%>>
    </a>
    <p><%= @items[4].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[5].link %> target="_blank" title=<%= @items[5].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[5].link%>>
    </a>
    <p><%= @items[5].title %></p>
  </div>
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[6].link %> target="_blank" title=<%= @items[6].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[6].link%>>
    </a>
    <p><%= @items[6].title %></p>
  </div>
  
  
  
  
  <!--
  <% @items.each do |item| %>
  <div class="item mt-3 col-md-3 thum">
    <%= link_to item.link do %>
      <%= image_tag "http://capture.heartrails.com/?" + item.link %>
    <% end %>
    <p><%= item.title %></p>
  </div>
<% end %>
  -->
  
  </div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="">
  <nav class="navbar navbar-expand-sm navbar-dark bg-info">
    <a class="navbar-brand" href="/">Sofia</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
         <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>   
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My_info', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sofia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
    
    
  </head>
  <body>
    <%= render 'layouts/navbar' %>
      <%= render 'layouts/flash_messages' %>
      <%= yield %>

  </body>
</html>

app/views/technology/index.html.erb
<ul class="nav nav-tabs nav-justified tech-tag" role="tablist">
    <li class="nav-item top-tag">
      <a class="nav-link bg-secondary text-white" href="/">トップ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-danger text-white" href="/anime/index">アニメ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-warning text-white" href="/game/index">ゲーム</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-success text-white" href="/economy/index">経済</a>
    </li>

    <li class="nav-item tech-tag">
      <a class="nav-link bg-primary text-white activate"href="/technology/index">テクノロジー</a>
    </li>
  </ul>




<!-- サムネイル表示場所-->

  <div class="row justify-content-around">
  

  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[1].link %> target="_blank" title=<%= @items[1].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[1].link%>>
    </a>
    <p><%= @items[1].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[2].link %> target="_blank" title=<%= @items[2].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[2].link%>>
    </a>
    <p><%= @items[2].title %></p>
  </div>
  
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[3].link %> target="_blank" title=<%= @items[3].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[3].link%>>
    </a>
    <p><%= @items[3].title %></p>
  </div>
  
  </div>
  
  
  <div class="row justify-content-around">
    
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[4].link %> target="_blank" title=<%= @items[4].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[4].link%>>
    </a>
    <p><%= @items[4].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[5].link %> target="_blank" title=<%= @items[5].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[5].link%>>
    </a>
    <p><%= @items[5].title %></p>
  </div>
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[6].link %> target="_blank" title=<%= @items[6].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[6].link%>>
    </a>
    <p><%= @items[6].title %></p>
  </div>
  
  
  
  
  <!--
  <% @items.each do |item| %>
  <div class="item mt-3 col-md-3 thum">
    <%= link_to item.link do %>
      <%= image_tag "http://capture.heartrails.com/?" + item.link %>
    <% end %>
    <p><%= item.title %></p>
  </div>
<% end %>
  -->
  
  </div>

app/views/toppages/index.html.erb
<ul class="nav nav-tabs nav-justified top-tag" role="tablist">
    <li class="nav-item top-tag">
      <a class="nav-link bg-secondary text-white activate" href="/">トップ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-danger text-white" href="/anime/index">アニメ</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-warning text-white" href="/game/index">ゲーム</a>
    </li>
    <li class="nav-item">
      <a class="nav-link bg-success text-white" href="/economy/index">経済</a>
    </li>

    <li class="nav-item">
      <a class="nav-link bg-primary text-white "href="/technology/index">テクノロジー</a>
    </li>
  </ul>


<!-- サムネイル表示場所-->

  <div class="row justify-content-around">
  

  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[1].link %> target="_blank" title=<%= @items[1].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[1].link%>>
    </a>
    <p><%= @items[1].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[2].link %> target="_blank" title=<%= @items[2].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[2].link%>>
    </a>
    <p><%= @items[2].title %></p>
  </div>
  
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[3].link %> target="_blank" title=<%= @items[3].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[3].link%>>
    </a>
    <p><%= @items[3].title %></p>
  </div>
  
  </div>
  
  
  <div class="row justify-content-around">
    
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[4].link %> target="_blank" title=<%= @items[4].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[4].link%>>
    </a>
    <p><%= @items[4].title %></p>
  </div>
  
  <div class="nav-item mt-3 col-md-3  thum">
    <a href=<%= @items[5].link %> target="_blank" title=<%= @items[5].title %>>
    <img class="col-md-12" src=<%= "http://capture.heartrails.com/?" + @items[5].link%>>
    </a>
    <p><%= @items[5].title %></p>
  </div>
  
 <div class="nav-item mt-3 col-md-3 thum">
    <a href=<%= @items[6].link %> target="_blank" title=<%= @items[6].title %>>
    <img class="col-md-12"  src=<%= "http://capture.heartrails.com/?" + @items[6].link%>>
    </a>
    <p><%= @items[6].title %></p>
  </div>
  
  
  
  
  <!--
  <% @items.each do |item| %>
  <div class="item mt-3 col-md-3 thum">
    <%= link_to item.link do %>
      <%= image_tag "http://capture.heartrails.com/?" + item.link %>
    <% end %>
    <p><%= item.title %></p>
  </div>
<% end %>
  -->
  
  </div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h3>時間があるときにユーザ画面でよく見る記事のレーダーチャート作ります(jsとか書くので今回は保留)
     <br>他のユーザの好みを覗けるように最終的にはする予定</br></h3>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3>時間があるときにユーザ画面でよく見る記事のレーダーチャート作ります(jsとか書くので今回は保留)</h3>
<h3>key word登録作成予定(URLのqueryに埋め込めばkeywordに合致する記事取得可能)</h3>